name: Test, Build and Push to Docker Hub

on:
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      # Grabs the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Sets up the Python 
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Run tests
      - name: Run tests
        env: 
          MODE: "test"
        run: |
          pytest src/tests.py

  
  build_deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Grabs the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Build Docker image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t serverless-py .